<?php

namespace AppBundle\Repository;

/**
 * DependenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenteRepository extends \Doctrine\ORM\EntityRepository
{
}
